language: c
compiler: gcc
os: linux

notifications:
  email: true

env:
  - MPI=openmpi

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install gsl-bin libgsl0-dev
  - sh ./conf/travis-install-mpi.sh $MPI

install:
  - sh ./conf/travis-install-fftw.sh
  - sh ./conf/travis-install-pfft.sh

script: ./bootstrap.sh && ./configure CPPFLAGS="-I$HOME/local/pfft/include -I$HOME/local/fftw/include" LDFLAGS="-L$HOME/local/pfft/lib -L$HOME/local/fftw/lib" FC=mpif90 CC=mpicc MPICC=mpicc MPIFC=mpif90 && make && make check

after_failure: "cat config.log"


